ninety-nine-cats/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "cats#index"
  resources :cats, except: [:destroy]
end

ninety-nine-cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

ninety-nine-cats/app/models/cat.rb
require 'action_view'

class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper
  CAT_COLORS = ["Black", "White", "Orange", "Brown"]

  validates :birth_date, presence: true
  validates :color, presence: true, inclusion: { in: CAT_COLORS }
  validates :name, presence: true
  validates :sex, presence: true, inclusion: { in: ["M", "F"] }
  validate :birth_date, :birth_date_cannot_be_future

  def birth_date_cannot_be_future
    if birth_date && birth_date > Date.today
      self.errors.add(:birth_date, "can't be in the future")
    end
  end

  def age
    cat_year = Date.today.year - birth_date.year
    cat_year -= 1 if Date.today < birth_date + cat_year.years
    
    if cat_year > 0 # return about x years
      return "About #{cat_year} years"
    else # return about x months
      cat_month = Date.today.month - birth_date.month
      return "About #{cat_month} months"
    end
  end
end

# about x years
# over x years
# about x months

ninety-nine-cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ninety-nine-cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index 
    @cats = Cat.all
    render :index 
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    render :show
  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def new
    @cat = Cat.new 
    render :new
  end

  def edit 
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update 
    @cat = Cat.find_by(id: params[:id])

    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit 
    end
  end

  private
  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end
end

ninety-nine-cats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninety-nine-cats/app/helpers/cats_helper.rb
module CatsHelper
end

ninety-nine-cats/app/views/cats/_form.html.erb
<% if type == :new %>
  <% action_url = cats_url %>
  <% button_text = 'Create Cat' %>
<% elsif type == :edit %>
  <% action_url = cat_url(@cat) %>
  <% button_text = 'Edit Cat' %>
<% end %>

<h1><%= button_text %></h1>

<form action="<%= action_url %>" method = "POST">
<% if type == :edit %>
  <input type="hidden" name="_method" value="PATCH">
<% end %>

  <label for="name">Name:</label>
  <input id="name" type="text" name="cat[name]" value="<%= cat.name %>">
  <br>

  <label for="sex">Sex:</label>
  <input id="sex" type="radio" name="cat[sex]" value="M" <%= cat.sex == "M" ? "checked" : ""%> >Male
  <input id="sex" type="radio" name="cat[sex]" value="F" <%= cat.sex == "F" ? "checked" : ""%> >Female
  <br>

  <label for="color">Color:</label>
  <select id="color" name="cat[color]">
    <option disabled <%= type == :new ? "selected" : "" %>>- Please Select Color-</option>
    <option value="Black" <%= cat.color == "Black" ? "selected" : ""%> >Black</option>
    <option value="White" <%= cat.color== "White" ? "selected" : "" %> >White</option>
    <option value="Orange" <%= cat.color== "Orange" ? "selected" : "" %>>Orange</option>
    <option value="Brown" <%= cat.color== "Brown" ? "selected" : "" %> >Brown</option>
  </select>
  <br>

  <label for="birth_date">Birthday:</label>
  <input id="birth_date" type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">
  <br>

  <label for="description">Description:</label>
  <textarea id="description" name="cat[description]" value="<%= cat.description %>"><%= cat.description %></textarea>
  <br>

  <input type="submit" value="<%= button_text %>"/>
</form>

ninety-nine-cats/app/views/cats/edit.html.erb
<%= render 'form', cat: @cat, type: :edit %>

ninety-nine-cats/app/views/cats/index.html.erb
<h1>All Cats</h1>

<% @cats.each do |cat| %>
  <p><%= cat.name %></p>
  <ul>
    <li><a href="<%= cat_url(cat)%>">Show <%= cat.name %></a></li>
  </ul>
<% end %>

ninety-nine-cats/app/views/cats/new.html.erb
<%= render 'form', cat: @cat, type: :new %>

ninety-nine-cats/app/views/cats/show.html.erb
<style>
  table, tr, td {
    border: 1px solid black;
  }
</style>

<h1><%= @cat.name %></h1>

<table>
  <thead>
    <tr>
      <th>Attribute</th>
      <th>Value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Age</td>
      <td><%= @cat.age %></td>
    </tr>
    <tr>
      <td>Birthday</td>
      <td><%= @cat.birth_date %></td>
    </tr>
    <tr>
      <td>Color</td>
      <td><%= @cat.color %></td>
    </tr>
    <tr>
      <td>Sex</td>
      <td><%= @cat.sex %></td>
    </tr>
    <tr>
      <td>Description</td>
      <td><%= @cat.description %></td>
    </tr>
  </tbody>
</table>

<br>
<a href="<%= cats_url%>">View all cats</a>

ninety-nine-cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>